version: "3.8"

services:
  api:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/project
    depends_on:
      - db

  db:
    image: postgres:13.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project

volumes:
  postgres_data: